# Generated by Django 2.1 on 2019-09-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WranglingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'x wrangling state',
            },
        ),
        migrations.RemoveField(
            model_name='assaytype',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assay_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cur_state',
        ),
        migrations.RemoveField(
            model_name='project',
            name='first_response_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='last_response_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='responders',
        ),
        migrations.AlterField(
            model_name='projectstate',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pmid',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.DeleteModel(
            name='AssayType',
        ),
        migrations.AddField(
            model_name='project',
            name='wrangling_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cur_state', to='hcat.WranglingState'),
        ),
    ]
