# Generated by Django 2.1 on 2019-09-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='staging_area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
