# Generated by Django 2.1 on 2019-09-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0002_auto_20190925_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='state_reached',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='project',
            name='wrangling_state',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hcat.WranglingState'),
        ),
    ]
