# Generated by Django 2.1 on 2019-09-26 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0003_auto_20190925_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='state',
            new_name='status',
        ),
    ]
