# Generated by Django 2.1 on 2019-09-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0005_auto_20190925_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WranglingState',
            new_name='WranglingStatus',
        ),
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name': 'x project status'},
        ),
        migrations.AlterModelOptions(
            name='wranglingstatus',
            options={'verbose_name': 'x wrangling status'},
        ),
    ]
