# Generated by Django 2.1 on 2019-09-26 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0006_auto_20190925_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='wrangling_state',
            new_name='wrangling_status',
        ),
    ]
