# Generated by Django 2.1 on 2019-09-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0007_auto_20190925_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectstatus',
            options={'verbose_name': 'x project status', 'verbose_name_plural': 'x project status'},
        ),
        migrations.AlterModelOptions(
            name='wranglingstatus',
            options={'verbose_name': 'x wrangling status', 'verbose_name_plural': 'x wrangling status'},
        ),
        migrations.RenameField(
            model_name='projectstatus',
            old_name='state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='wranglingstatus',
            old_name='state',
            new_name='status',
        ),
    ]
