# Generated by Django 2.1 on 2019-09-26 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0008_auto_20190925_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='wrangler1',
            new_name='primary_wrangler',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='wrangler2',
            new_name='secondary_wrangler',
        ),
    ]
