# Generated by Django 2.1 on 2019-09-26 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0009_auto_20190925_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='secondary_wrangler',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_wrangler', to='hcat.Wrangler'),
        ),
    ]
