# Generated by Django 2.1 on 2019-10-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0011_auto_20190927_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.AddField(
            model_name='project',
            name='wrangler_drive',
            field=models.URLField(blank=True),
        ),
    ]
