# Generated by Django 2.1 on 2019-10-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0012_auto_20191008_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('projects', models.ManyToManyField(blank=True, to='hcat.Project')),
            ],
            options={
                'verbose_name': 'x project tag',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hcat.Tag'),
        ),
    ]
