# Generated by Django 2.1 on 2019-10-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0013_auto_20191008_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='effort',
            new_name='project_source',
        ),
    ]
