# Generated by Django 2.1 on 2019-10-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0014_auto_20191008_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EffortType',
            new_name='ProjectSourceType',
        ),
        migrations.AlterModelOptions(
            name='projectsourcetype',
            options={'verbose_name': 'x project source type'},
        ),
    ]
