# Generated by Django 2.1 on 2019-10-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0016_auto_20191008_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssayTech',
            new_name='CdnaLibraryPrep',
        ),
    ]
