# Generated by Django 2.1 on 2019-10-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0017_auto_20191008_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assay_tech',
            new_name='cdna_library_prep',
        ),
        migrations.AlterField(
            model_name='cdnalibraryprep',
            name='projects',
            field=models.ManyToManyField(blank=True, to='hcat.Project'),
        ),
    ]
