# Generated by Django 2.1 on 2019-10-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0018_auto_20191008_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cdna_library_prep',
            field=models.ManyToManyField(blank=True, to='hcat.CdnaLibraryPrep', verbose_name='cDNA library prep'),
        ),
    ]
