# Generated by Django 2.1 on 2019-10-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0019_auto_20191008_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('comments', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'x preservation method',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='cdna_library_prep',
            field=models.ManyToManyField(blank=True, to='hcat.CdnaLibraryPrep', verbose_name=' cDNA library prep'),
        ),
        migrations.AddField(
            model_name='project',
            name='preservation_method',
            field=models.ManyToManyField(blank=True, to='hcat.PreservationMethod'),
        ),
    ]
