# Generated by Django 2.1 on 2019-10-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0020_auto_20191008_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdnalibraryprep',
            options={'verbose_name': 'x cDNA library prep'},
        ),
    ]
