# Generated by Django 2.1 on 2020-07-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0021_auto_20191016_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('submitter_name', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('links', models.URLField()),
                ('summary', models.TextField()),
            ],
            options={
                'verbose_name': 'x suggested_project',
            },
        ),
    ]
