# Generated by Django 2.1 on 2020-11-23 19:26

from django.db import migrations
from django.conf import settings

def update_site_name(apps, schema_editor):
    sitemodel = apps.get_model('sites', 'Site')
    name = 'Tuatara'
    domain = 'tuatara.gi.ucsc.edu/'

    sitemodel.objects.update_or_create(
        pk=settings.SITE_ID,
        defaults={'domain': domain,
                  'name': name}
    )

class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0022_suggestedprojects'),
    ]

    operations = [
    ]
