# Generated by Django 2.1 on 2020-11-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0022_suggestedprojects'),
    ]

    operations = [
    ]
