# Generated by Django 2.1 on 2020-12-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0023_UPDATE_SITE_NAME'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consent',
            new_name='Privacy',
        ),
        migrations.AlterModelOptions(
            name='privacy',
            options={'verbose_name': 'x privacy'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='consent',
            new_name='privacy',
        ),
    ]
