# Generated by Django 2.1 on 2020-12-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcat', '0024_auto_20201204_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='wrangler_drive',
            new_name='google_drive_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='shared_google_sheet',
            new_name='google_sheet_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='origin_name',
            new_name='source_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='git_ticket_url',
            new_name='ticket_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='staging_area',
            new_name='file_bucket'
        ),
    ]
